joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

mobile_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['front_left_wheel_joint', 'rear_left_wheel_joint']
  right_wheel: ['front_right_wheel_joint', 'rear_right_wheel_joint']
  publish_rate: 50
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 0.25
  velocity_rolling_window_size: 2

  # Publish output cmd_vel for debugging
  publish_cmd: true

  # Base frame_id
  base_frame_id: base_link
  
  # Let robot_localization handle the odometry TF
  enable_odom_tf: false

  # Wheel separation and radius multipliers
  wheel_separation: 0.25
  wheel_radius: 0.075
  wheel_separation_multiplier: 1.0
  wheel_radius_multiplier: 1.0

  # Velocity and acceleration limits
  linear:
    x:
      has_velocity_limits: true
      max_velocity: 0.5   # m/s
      min_velocity: -0.5
      has_acceleration_limits: true
      max_acceleration: 2.5   # m/s^2
      min_acceleration: -2.5
  angular:
    z:
      has_velocity_limits: true
      max_velocity: 3.5   # rad/s
      min_velocity: -3.5
      has_acceleration_limits: true
      max_acceleration: 5.0   # rad/s^2
      min_acceleration: -5.0
