# costmap_common_params.yaml
footprint: [[-0.5, -0.3], [-0.5, 0.3], [0.5, 0.3], [0.5, -0.3]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
  map_topic: /map
  subscribe_to_updates: true

obstacles_laser:
  observation_sources: laser
  laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true}

inflation:
  inflation_radius: 0.3

# local_costmap_params.yaml
local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: false
  rolling_window: true
  width: 3.0
  height: 3.0
  resolution: 0.05
  

# global_costmap_params.yaml
global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish frequency: 5.0
  static_map: true
  transform_tolerance: 0.5

# base_local_planner_params.yaml
DWAPlannerROS:
# robot Configuration parameters
  max_vel_x: 0.20
  min_vel_x: 0.08

  max_vel_y: 0.0
  min_vel_y: 0.0
#robot velocity on a straight line
  max_vel_trans: 0.5
  min_vel_trans: 0.1

#robot angular velocity around an axis
  max_vel_theta: 1.0
  min_vel_theta: 0.2

  acc_lim_x: 2.5
  acc_lim_y: 0.0
  acc_lim_theta: 3.2
 
# goal tolerance parameters
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

#forward simulation parameters
  sim_time: 1.7
  vx_samples: 3
  vy_samples: 0
  vtheta_samples: 20
  controller_frequency: 20.0

# trajectory scoring parameters
  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.1
  forward_point_distance: 0.325
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# ocillation prevention parameters
  oscillation_reset_dist: 0.05

# global plan parameters
  prune_plan: true

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true